controllers:
  resource: ../src/Shared/Infrastructure/Controller/
  type: annotation

kernel:
  resource: ../src/Shared/Infrastructure/Kernel.php
  type: annotation

api_login_check:
  path: /api/auth/token/login

gesdinet_jwt_refresh_token:
  path: /api/auth/token/refresh
#  controller: gesdinet.jwtrefreshtoken::refresh

users:
  resource: ../src/Users/Infrastructure/Controller/
  type: annotation